In [29]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [30]:
df = pd.DataFrame({'Date':['2026-10-26','2025-06-29','2024-02-12','2026-09-22','2023-03-16']})

In [31]:
df

         Date
0  2026-10-26
1  2025-06-29
2  2024-02-12
3  2026-09-22
4  2023-03-16

In [32]:
df.dtypes

Date    object
dtype: object

In [33]:
df['Date']= pd.to_datetime(df['Date'])

In [34]:
df.dtypes

Date    datetime64[ns]
dtype: object

In [35]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
df

        Date  Year  Month  Day
0 2026-10-26  2026     10   26
1 2025-06-29  2025      6   29
2 2024-02-12  2024      2   12
3 2026-09-22  2026      9   22
4 2023-03-16  2023      3   16

In [36]:
df.drop('Date', axis=1,inplace= True)

In [37]:
df

   Year  Month  Day
0  2026     10   26
1  2025      6   29
2  2024      2   12
3  2026      9   22
4  2023      3   16